### ISSUE TITLE
Move from Code Igniter

### ISSUE THREAD

**Issue by sirreal** [hermzz/gestorneo#18]
Code igniter seems to be practically abandoned and is limited to begin with. How about moving to a different framework?

**Comment by sirreal** [comment]
I've used [Yii](http://www.yiiframework.com/) on a few projects and I was pleased. It's under active development and [Yii2](https://github.com/yiisoft/yii2/issues/milestones) is close to realease, which seems to be a major overhaul.

I also spoke to @layoutd and @hermzz about [Laravel](http://laravel.com). I have no experience with it, but it looks pretty interesting.

**Comment by hermzz** [comment]
I like the look of Laravel. The symfony-like alternative I mentioned is [Silex](http://silex.sensiolabs.org/).
