### ISSUE TITLE
Tournament name error when using &

### ISSUE THREAD

**Issue by ghost** [hermzz/gestorneo#7]
In the title of the "In&Out" tournament appears ";" after the title.

**Comment by sirreal** [comment]
This is a bug in CI xss sanitization. Just have to leave a space after &

https://github.com/EllisLab/CodeIgniter/issues/1261

**Comment by bdmunna** [comment]
Set $config['global_xss_filtering'] = FALSE; and use $this->input->post('var', TRUE) where need to filter XSS.
